/* CIE 9618 Paper 1 — sample SQL scripts for sql-ide.html */
(function (global) {
  'use strict';

  global.SQL_SAMPLES = {
    school: `-- Minimal school database (textbook style)
CREATE DATABASE School;

CREATE TABLE Class(ClassID CHARACTER, Location CHARACTER, LicenceNumber CHARACTER);
ALTER TABLE Class ADD PRIMARY KEY (ClassID);

CREATE TABLE Student(StudentID CHARACTER, FirstName CHARACTER, SecondName CHARACTER, DateOfBirth DATE, ClassID CHARACTER);
ALTER TABLE Student ADD PRIMARY KEY (StudentID);
ALTER TABLE Student ADD FOREIGN KEY (ClassID) REFERENCES Class(ClassID);

CREATE TABLE Subject(SubjectName CHARACTER, LicenceNumber CHARACTER);
ALTER TABLE Subject ADD PRIMARY KEY (SubjectName);

CREATE TABLE Teacher(TeacherName CHARACTER, LicenceNumber CHARACTER);
ALTER TABLE Teacher ADD PRIMARY KEY (LicenceNumber);

INSERT INTO Class VALUES('7A', 'Room 12', 'L001');
INSERT INTO Student VALUES('S101', 'Alice', 'Adams', '2008-03-14', '7A');
INSERT INTO Student VALUES('S102', 'Bob', 'Brown', '2008-07-22', '7A');
INSERT INTO Subject VALUES('Physics', 'L001');
INSERT INTO Teacher VALUES('Mr Smith', 'L001');

SELECT FirstName, SecondName
FROM Student
WHERE ClassID = '7A'
ORDER BY SecondName;`,

    library: `-- Library LOAN database (exam-style)
CREATE DATABASE Library;

CREATE TABLE MEMBER(MemberID CHARACTER, MemberName CHARACTER, MemberPhone CHARACTER);
ALTER TABLE MEMBER ADD PRIMARY KEY (MemberID);

CREATE TABLE BOOK(BookID CHARACTER, Title CHARACTER, Author CHARACTER);
ALTER TABLE BOOK ADD PRIMARY KEY (BookID);

CREATE TABLE LOAN(LoanID CHARACTER, BookID CHARACTER, MemberID CHARACTER, Returned BOOLEAN, LoanDate DATE);
ALTER TABLE LOAN ADD PRIMARY KEY (LoanID);
ALTER TABLE LOAN ADD FOREIGN KEY (BookID) REFERENCES BOOK(BookID);
ALTER TABLE LOAN ADD FOREIGN KEY (MemberID) REFERENCES MEMBER(MemberID);

INSERT INTO MEMBER VALUES('M104', 'Jane Doe', '57123456');
INSERT INTO MEMBER VALUES('M105', 'John Smith', '57234567');
INSERT INTO BOOK VALUES('B01', 'Introduction to Algorithms', 'Cormen');
INSERT INTO BOOK VALUES('B02', 'Database Design', 'Connolly');
INSERT INTO LOAN VALUES('L01', 'B01', 'M104', FALSE, '2024-01-15');
INSERT INTO LOAN VALUES('L02', 'B02', 'M104', TRUE, '2024-02-01');
INSERT INTO LOAN VALUES('L03', 'B01', 'M105', FALSE, '2024-03-10');

SELECT BOOK.Title, BOOK.Author
FROM BOOK INNER JOIN LOAN ON BOOK.BookID = LOAN.BookID
WHERE LOAN.Returned = FALSE
ORDER BY BOOK.Title;

SELECT COUNT(*) AS NumberOfLoans
FROM LOAN
WHERE MemberID = 'M104';`,

    tuition: `-- Extended tuition centre database
CREATE DATABASE CurepipeStudy;

CREATE TABLE TUTOR(
    TutorID CHARACTER,
    TutorName CHARACTER,
    TutorPhone CHARACTER);
ALTER TABLE TUTOR ADD PRIMARY KEY (TutorID);

CREATE TABLE CLASS(
    ClassCode CHARACTER,
    Room VARCHAR(40),
    TutorID CHARACTER);
ALTER TABLE CLASS ADD PRIMARY KEY (ClassCode);
ALTER TABLE CLASS ADD FOREIGN KEY (TutorID) REFERENCES TUTOR(TutorID);

CREATE TABLE SUBJECT(
    SubjectName CHARACTER,
    SubjectTeacher CHARACTER);
ALTER TABLE SUBJECT ADD PRIMARY KEY (SubjectName);

CREATE TABLE STUDENT(
    StudentID CHARACTER,
    FirstName CHARACTER,
    LastName CHARACTER,
    DateOfBirth DATE,
    ClassCode CHARACTER);
ALTER TABLE STUDENT ADD PRIMARY KEY (StudentID);
ALTER TABLE STUDENT ADD FOREIGN KEY (ClassCode) REFERENCES CLASS(ClassCode);

CREATE TABLE STUDENT_SUBJECT(
    StudentID CHARACTER,
    SubjectName CHARACTER,
    ExamMark INTEGER);
ALTER TABLE STUDENT_SUBJECT ADD PRIMARY KEY (StudentID, SubjectName);
ALTER TABLE STUDENT_SUBJECT ADD FOREIGN KEY (StudentID) REFERENCES STUDENT(StudentID);
ALTER TABLE STUDENT_SUBJECT ADD FOREIGN KEY (SubjectName) REFERENCES SUBJECT(SubjectName);

INSERT INTO TUTOR VALUES('T01', 'Mr Rougier', '57111111');
INSERT INTO CLASS VALUES('C5A', 'Room 3', 'T01');
INSERT INTO SUBJECT VALUES('Physics', 'Mr Rougier');
INSERT INTO STUDENT VALUES('S101', 'Nicolas', 'Rougier', '2008-11-08', 'C5A');
INSERT INTO STUDENT VALUES('S102', 'Fabrice', 'Ah-Sen', '2008-05-12', 'C5A');
INSERT INTO STUDENT_SUBJECT VALUES('S101', 'Physics', 78);
INSERT INTO STUDENT_SUBJECT VALUES('S102', 'Physics', 85);

SELECT ClassCode, COUNT(StudentID) AS NumberOfPupils
FROM STUDENT
GROUP BY ClassCode;`
  };
})(typeof window !== 'undefined' ? window : globalThis);
